### ISSUE TITLE
Token verification is hard-coded to production

### ISSUE THREAD

**Issue by benlangfeld** [powerhome/omniauth-nitro-id#45]
`OmniAuth::Strategies::NitroId.decode_logout_token`, `OmniAuth::Strategies::NitroId.fetch_jwks` and `OmniAuth::Strategies::NitroId.introspect_token` all use `default_options`, resolving the issuer to `id.powerhrg.com` (or similar for Stream Financial) regardless of any configuration override passed to `OmniAuth::Builder`.

This means I am unable to use the strategy to debug client applications against instances of NitroID other than the production ones.

**Comment by phylum** [comment]
@benlangfeld Thanks! We have a [ticket](https://runway.powerhrg.com/backlog_items/SHD-1009) to address this.

**Comment by web-kat** [comment]
This has been addressed in #46 and released in v1.4.0. Closing.
